name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to fill out the entire form below, providing as much context as you can in order to help us triage and track down your bug as quickly as possible.
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide as much detail as you reasonably can.
      value: |
        ## Description

        ## Expected Result

        ## Actual Result

    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce it?
      description: Please provide steps to reproduce the issue.
      value: |
        1. 
        2. 
        3. 
        4. 

    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment information
      description: Please provide any additional information about your installation, and version you are using.
      value: |
        ## Environment
        OS: (e.g., "Ubuntu 20.04")
        Compiler(if manually compiled): (e.g., "go 14.2")
        Version: (e.g., "v1.0.0")

  - type: textarea
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output.
      render: shell
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.
