name: Question
description: Ask a question about the project
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Describe your question
      description: A clear and concise description of what the question is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the question here.
    validations:
      required: false