
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "This is an AWS Lambda function that collects CloudWatch logs and sends them to Logz.io in bulk, over HTTP."
Parameters:
  LogzioURL:
    Type: "String"
    Description: "Deprecated. Use LogzioREGION instead"
    Default: ""

  LogzioREGION:
    Type: "String"
    Description: "Two-letter region code, or blank for US East (Northern Virginia). This determines your listener URL
    (where you're shipping the logs to) and API URL. You can find your region code in the Regions and URLs at
    https://docs.logz.io/user-guide/accounts/account-region.html#regions-and-urls table"
    Default: "us"

  LogzioTOKEN:
    Type: "String"
    Description: "Logz.io account token."

  LogzioTYPE:
    Type: "String"
    Description: "The log type you'll use with this Lambda.
    Please note that you should create a new Lambda for each log type you use.
    This can be a built-in log type, or your custom log type"
    Default: "logzio_cloudwatch_lambda"

  LogzioFORMAT:
    Type: "String"
    Description: "json or text.
    If json, the lambda function will attempt to parse the message field as JSON
    and populate the event data with the parsed fields."
    Default: "text"

  LogzioCOMPRESS:
    Type: "String"
    Description: "If true, the Lambda will send compressed logs. If false, the Lambda will send uncompressed logs."
    Default: "false"

  LogzioENRICH:
    Type: "String"
    Description: "Enriches the CloudWatch events with custom properties at ship time. The format is `key1=value1;key2=value2`. By default is empty."
    Default: ""

Outputs:
    LogzioCloudwatchLogsLambda:
      Description: "Logz.io CW logs lambda ARN"
      Value: !GetAtt LogzioCloudwatchLogsLambda.Arn

Resources:
  LogzioCloudwatchLogsLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: lambda_function.lambda_handler
      CodeUri: ./dist/logzio-cloudwatch.zip
      FunctionName: logzio-cloudwatch-log-shipper
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          REGION: !Ref LogzioREGION
          URL: !Ref LogzioURL
          TOKEN: !Ref LogzioTOKEN
          TYPE: !Ref LogzioTYPE
          FORMAT: !Ref LogzioFORMAT
          COMPRESS: !Ref LogzioCOMPRESS
          ENRICH: !Ref LogzioENRICH